
version: '2.1'
services:
  base-rsync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_HOST_NAME:-standalone.rsync}
    hostname: ${CONTAINER_HOST_NAME:-standalone.rsync}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-rsync}:${IMAGE_TAG:-latest}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.rsync}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/rsync/standalone}
